query contentQuery($relativePath: String!) {
  page(relativePath: $relativePath) {
    ...PageParts
  }
}

query postQuery($relativePath: String!) {
  post(relativePath: $relativePath) {
    ...PostParts
  }
}

query postsLatestsQuery {
  postConnection(sort: "publishedAt", filter: { draft: { eq: false } }) {
    edges {
      node {
        title
        summary
        category
        tags {
          options
        }
        publishedAt
        _sys {
          relativePath
        }
      }
    }
  }
}
