query contentQuery($relativePath: String!) {
  page(relativePath: $relativePath) {
    ...PageParts
  }
}

query postQuery($relativePath: String!) {
  post(relativePath: $relativePath) {
    ...PostParts
  }
}
